#!/bin/bash
#
# Steve Barcomb (sbarcomb@redhat.com)


caseno=$1
filename=$2
casenolen=$(echo -n $caseno | wc -m)
dir=
user=
passwd=


aria=$(command -v aria2c)

if [ -z $aria ]
then
	echo Please install aria2
else
	mkdir $dir/$caseno
	echo Downloading files to $dir/$caseno
fi

aria2c --allow-overwrite=true --http-user $user --http-passwd $passwd -d $dir/$caseno https://access.redhat.com/rs/cases/$caseno/attachments

if [ -n $filename ]
then
	single=$(grep -B 1 "<fileName>$filename" $dir/$caseno/attachments | head -n1 | sed -e 's|^[ \t]*||' | sed -e 's|<uri>||g' | sed -e 's|</uri>||g')
	echo $single
	aria2c -x 16 -j 16 --force-save=true --allow-overwrite=false --summary-interval 0 -d $dir/$caseno --http-user $user --http-passwd $passwd $single

else
	grep uri $dir/$caseno/attachments |  sed -e 's|^[ \t]*||' | sed -e 's|<uri>||g' | sed -e 's|</uri>||g' > $dir/$caseno/.attachments_cleaned
	aria2c -x 16 -j 16 --force-save=true --allow-overwrite=false --summary-interval 0 -d $dir/$caseno --http-user $user --http-passwd $passwd -i $dir/$caseno/.attachments_cleaned
fi
